### ISSUE TITLE
Bad first argument of \catcode, \lccode etc is silently turned to something else

### ISSUE THREAD

**Issue by blefloch** [texjporg/uptex-base#1]
In upTeX (and eupTeX), giving some bad (first) argument in a `\catcode` or `\lccode` assignment seems to behave as if the first argument was the second least-significant byte.  This would be fine if an error was raised, like in usual TeX.

```
\message{\the\catcode0} % 9
\catcode65536=1
\message{\the\catcode0} % 1

\message{\the\lccode0} % 0
\lccode65536=123
\message{\the\lccode0} % 123

\message{\meaning A} % the letter A
\catcode"ABC41DE=12
\message{\meaning A} % the character A
```

The `\kcatcode` primitive seems to behave more weirdly.  For instance in eupTeX,

```
\tracingall
\message{\the\kcatcode160} % 18
\kcatcode65536=19 % {changing \kcatcode160=18} {into \kcatcode160=19}
\message{\the\kcatcode160} % 18
\message{\the\kcatcode65536} % 19
\kcatcode65537=18
\message{\the\kcatcode65536} % 18
```

**Comment by h-kitagawa** [comment]
> In upTeX (and eupTeX), giving some bad (first) argument in a \catcode or \lccode assignment seems to behave as if the first argument was the second least-significant byte. 

If the argument in querying \catcode etc. is a KANJI code, pTeX treats it as its high-order byte.
The following is an example:
```
\catcode"B1=1
\message{\the\catcode"A1B1}
```
I found pTeX-2.1.4 (about 1995) already has this behavior,
but I don't know whether this is an intentional specification, or a simple hack for avoiding an error.

The current  behavior in assignments
> ```
\catcode"ABC41DE=12
\message{\meaning A} % the character A
```

is introduced due to the above "specification", in [r24874](http://www.tug.org/svn/texlive?view=revision&revision=24874) of TeX Live SVN (Dec 19, 2011).

> This would be fine if an error was raised, like in usual TeX.
I agree with you.

**Comment by h-kitagawa** [comment]
In [r41998](http://www.tug.org/svn/texlive?view=revision&revision=41998) of TeX Live SVN, `\catcode`, `\lccode`, `\uccode`, `\sfcode` in (e-)(u)pTeX now accept only 0--255.

**Comment by blefloch** [comment]
Thank you very much for the speed.  Presumably the issue can then be closed?
